name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout repository
      uses: ./.github/actions/checkout

    - name: Install Rust
      run: sudo apt update && sudo apt install rustc cargo

    - name: Install mdBook
      run: cargo install mdbook

    - name: Build the book
      run: mdbook build

    - name: Deploy to GitHub Pages
      uses: ./.github/actions/gh-pages
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./book
